In [1]:
import numpy as np

In [12]:
np.arange(0,11) - np.arange(22,33)

array([-22, -22, -22, -22, -22, -22, -22, -22, -22, -22, -22])

# * is not array multiplication

In [11]:
np.arange(0,10).reshape(5,2) * np.arange(22,32).reshape(5,2)

array([[  0,  23],
       [ 48,  75],
       [104, 135],
       [168, 203],
       [240, 279]])

In [14]:
np.arange(0,10).reshape(5,2) / np.zeros((5,2))

/home/harsh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/home/harsh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, inf],
       [inf, inf],
       [inf, inf],
       [inf, inf],
       [inf, inf]])

In [15]:
arr = np.arange(0,10).reshape(5,2)

In [16]:
np.exp(arr)

array([[1.00000000e+00, 2.71828183e+00],
       [7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03]])

In [17]:
np.sqrt(arr)

array([[0.        , 1.        ],
       [1.41421356, 1.73205081],
       [2.        , 2.23606798],
       [2.44948974, 2.64575131],
       [2.82842712, 3.        ]])

In [18]:
np.max(arr)

9

In [19]:
np.log(arr)

/home/harsh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        ],
       [0.69314718, 1.09861229],
       [1.38629436, 1.60943791],
       [1.79175947, 1.94591015],
       [2.07944154, 2.19722458]])

In [20]:
np.cos(arr)

array([[ 1.        ,  0.54030231],
       [-0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225],
       [-0.14550003, -0.91113026]])