In [1]:
li = [1,2,3]

In [2]:
import numpy as np

In [3]:
np.array(li)

array([1, 2, 3])

In [4]:
mat=[[1,2,3],[4,5,6]]

In [5]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.arange(0,100,7)

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [10]:
np.zeros((4,5,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [11]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5,5)

array([[0.22085431, 0.50696124, 0.95826766, 0.25567463, 0.86085885],
       [0.81155276, 0.64272511, 0.39272235, 0.69390517, 0.35693357],
       [0.03786079, 0.9366512 , 0.80502211, 0.66883994, 0.12043322],
       [0.6218261 , 0.71135943, 0.13318048, 0.95037858, 0.57354543],
       [0.30694864, 0.2385719 , 0.49481095, 0.90208934, 0.88135915]])

In [17]:
np.random.randn(4,5)

array([[ 0.08829018, -2.17539123,  0.47608561, -0.35458202, -0.24509134],
       [ 0.31709753, -0.59776438, -0.66194155,  0.31568327, -1.04014887],
       [-0.3957826 ,  0.19790923,  0.08293338,  1.10947744,  0.18138285],
       [-1.02131795,  0.45253429,  0.35658877,  1.21159684, -2.5788995 ]])

In [22]:
np.random.randint(1,100)

68

In [23]:
np.random.randint(2,100,(12,3))

array([[ 8, 82, 75],
       [51, 42, 24],
       [85, 59, 31],
       [72, 65, 69],
       [20, 39, 58],
       [69, 94, 18],
       [53, 62, 20],
       [41, 84, 49],
       [49, 46, 35],
       [ 6, 80, 92],
       [57, 89, 88],
       [78, 63, 13]])

In [27]:
np.random.randint(1,100,16).reshape(2,2,4)

array([[[72, 34, 72, 41],
        [48, 78, 50, 61]],

       [[ 4, 87, 68, 37],
        [83, 17, 69, 37]]])

In [28]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
np.arange(0,25).reshape(5,5).max()

24

In [30]:
np.arange(0,25).reshape(5,5).min()

0

In [31]:
np.arange(0,25).reshape(5,5).argmin()

0

In [32]:
np.arange(0,25).reshape(5,5).argmax()

24

In [34]:
np.arange(0,20).reshape(2,2,5).shape

(2, 2, 5)

In [35]:
np.arange(0,20).reshape(2,2,5).dtype

dtype('int64')