In [1]:
import numpy as np

In [2]:
np.arange(24)[23]

23

In [9]:
np.random.randint(0,10,(3,4))[2][2]

8

In [11]:
np.random.randint(0,100,(13,24))[4,12]

92

In [17]:
arr = np.arange(24)

In [18]:
arr[2:4]

array([2, 3])

In [19]:
arr[6:17]=100

In [20]:
arr

array([  0,   1,   2,   3,   4,   5, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100,  17,  18,  19,  20,  21,  22,  23])

In [22]:
arr

array([[0.28618994, 0.84001808, 0.44405967, 0.04236057],
       [0.78707948, 0.68041125, 0.07719374, 0.88093441],
       [0.49926513, 0.04848146, 0.84353132, 0.07509912]])

In [25]:
arr.reshape(4,3)

array([[0.28618994, 0.84001808, 0.44405967],
       [0.04236057, 0.78707948, 0.68041125],
       [0.07719374, 0.88093441, 0.49926513],
       [0.04848146, 0.84353132, 0.07509912]])

In [26]:
arr= np.arange(23)

In [27]:
arr_ref = arr[5:9]

In [28]:
arr_ref[:]=10000

In [29]:
arr_ref

array([10000, 10000, 10000, 10000])

In [30]:
arr

array([    0,     1,     2,     3,     4, 10000, 10000, 10000, 10000,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22])

### Changes in arr_ref will affect arr. so we must make a copy

In [31]:
arr_ref = arr.copy()[5:9]
arr_ref[:]=np.arange(5,9)

In [32]:
arr_ref

array([5, 6, 7, 8])

In [33]:
arr

array([    0,     1,     2,     3,     4, 10000, 10000, 10000, 10000,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22])

## now with 2d

In [36]:
arr = np.random.randint(2,10,20).reshape(4,5)

In [38]:
arr

array([[9, 7, 9, 2, 9],
       [7, 5, 5, 9, 9],
       [8, 5, 3, 8, 5],
       [6, 2, 2, 6, 3]])

In [40]:
arr[3,1]

2

In [54]:
arr_col = arr.copy()[:][1:2]

In [55]:
arr_col

array([[7, 5, 5, 9, 9]])

In [59]:
arr_col[:]= np.random.randint(451,567,arr_col.shape)

In [60]:
arr_col

array([[457, 499, 511, 506, 485]])

In [63]:
arr_subs = arr.copy()[:4,1:3]

In [64]:
arr_subs

array([[7, 9],
       [5, 5],
       [5, 3],
       [2, 2]])

In [66]:
arr_subs > 6

array([[ True,  True],
       [False, False],
       [False, False],
       [False, False]])

In [68]:
arr_subs[arr_subs > 2]

array([7, 9, 5, 5, 5, 3])